# Install Poetry, dependencies, run tests with a range of Python versions on Ubuntu Linux

name: Python package with Poetry

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install project
      run: poetry install --without dev  # installs main and test groups
    - name: Lint with isort
      # by default: exit with error if imports are not properly sorted; show diffs
      uses: isort/isort-action@master
    - name: Lint with black
      # by default: exit with error if code is not properly formatted; show diffs
      uses: psf/black@stable
    - name: Lint with ruff
      # by default: exit with error if rule violations
      uses: chartboost/ruff-action@v1
    - name: Check typing with mypy
      run: |
        source $VENV
        mypy .
